# Generated by Django 5.1.3 on 2024-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sanho', models.CharField(max_length=200)),
                ('user_selected_date', models.DateField()),
                ('category', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy'), ('trans_bank', 'Bank Transfer'), ('other', 'Other')], default='sell', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('memo', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-user_selected_date',),
            },
        ),
    ]
